name: Copy Files to Second Branch

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout both branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can switch branches

      - name: Copy files from main to second
        run: |
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Save current branch (main)
          CURRENT_BRANCH=$(git branch --show-current)

          # Copy the file we want to move
          cp SourceFolder/sourceFile.xml /tmp/sourceFile.xml

          # Switch to second branch
          git checkout second

          # Copy the file into place
          cp /tmp/sourceFile.xml SourceFolder/sourceFile.xml

          # Add, commit and push changes
          git add SourceFolder/sourceFile.xml
          git commit -m "Copied sourceFile.xml from $CURRENT_BRANCH to second"
          git push origin second
