name: Copy File to Second Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <--- important for pushing

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy file from main to second branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          CURRENT_BRANCH=$(git branch --show-current)

          cp .github/SourceFolder/sourceFile.xml /tmp/sourceFile.xml

          git checkout second

          mkdir -p .github/SourceFolder

          cp /tmp/sourceFile.xml .github/SourceFolder/sourceFile.xml

          git add .github/SourceFolder/sourceFile.xml
          git commit -m "Copied sourceFile.xml from $CURRENT_BRANCH to second" || echo "No changes to commit"
          git push origin second
