name: Copy Files to Second Branchs

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Check if source folder exists
        id: check_folder
        run: |
          if [ -d .github/SourceFolder ]; then
            echo "Folder exists"
            echo "::set-output name=exists::true"
          else
            echo "Folder does not exist"
            echo "::set-output name=exists::false"
          fi

      - name: Checkout second branch
        uses: actions/checkout@v3
        with:
          ref: second  # Updated branch name

      - name: Ensure target folder exists
        run: |
          if [ ! -d .github/SourceFolder ]; then
            mkdir -p .github/SourceFolder
          fi

      - name: Copy files to second branch
        run: |
          cp -r ../.github/SourceFolder/* .github/SourceFolder/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .github/SourceFolder
          git commit -m "Copied files from main to second"
          git push


