name: Copy File to Second Branch

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to checkout other branches

      - name: Copy file from main to second branch
        run: |
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Save current branch
          CURRENT_BRANCH=$(git branch --show-current)

          # Copy the source file temporarily
          cp .github/SourceFolder/sourceFile.xml /tmp/sourceFile.xml

          # Switch to second branch
          git checkout second

          # Ensure the folder exists (optional safety)
          mkdir -p .github/SourceFolder

          # Copy the file into the folder
          cp /tmp/sourceFile.xml .github/SourceFolder/sourceFile.xml

          # Git add, commit and push
          git add .github/SourceFolder/sourceFile.xml
          git commit -m "Copied sourceFile.xml from $CURRENT_BRANCH to second"
          git push origin second
